name: Build Docker Image

on: [push, pull_request]

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
